### ISSUE TITLE
Error with docker and traefik 

### ISSUE THREAD

**Issue by kevingrondin** [calcom/cal.com#11260]
### Issue Summary

When running the `calcom` application using the official Docker Hub image, we encounter several issues, including errors during script execution and missing dependencies.

### Steps to Reproduce

1. Run the `calcom` service using the provided Docker-compose.
2. View the logs of the `calcom` container using the command `sudo docker logs calcom`.

### Actual Results

We obtained the following results:

> ℹ️ For this log I replace my real domain name by website 

```yaml
+ scripts/replace-placeholder.sh http://localhost:3000 https://calcom.website.re
Replacing all statically built instances of http://localhost:3000 with https://calcom.website.re.
+ scripts/wait-for-it.sh -- echo database is up
Error: you need to provide a host and port to test.
Usage:
  scripts/wait-for-it.sh host:port|url [-t timeout] [-- command args]
  -q | --quiet                        Do not output any status messages
  -t TIMEOUT | --timeout=timeout      Timeout in seconds, zero for no timeout
  -- COMMAND ARGS                     Execute command with args after the test finishes
+ npx prisma migrate deploy --schema /calcom/packages/prisma/schema.prisma
Prisma schema loaded from packages/prisma/schema.prisma
Datasource "db": PostgreSQL database "calcom_db", schema "public" at "postgres-calcom:5432"

207 migrations found in prisma/migrations

No pending migrations to apply.
npm notice 
npm notice New major version of npm available! 9.6.7 -> 10.1.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.1.0>
npm notice Run `npm install -g npm@10.1.0` to update!
npm notice 
+ npx ts-node --transpile-only /calcom/packages/prisma/seed-app-store.ts
📲 Updated app: 'apple-calendar'
📲 Updated app: 'caldav-calendar'
Error adding google credentials to DB: Unexpected end of JSON input
📲 Updated app: 'jitsi'
📲 Updated app: 'wipe-my-cal'
📲 Updated app: 'make'
📲 Updated app: 'huddle01'
📲 Updated app: 'amie'
📲 Updated app: 'apple-calendar'
📲 Updated app: 'around'
📲 Updated app: 'basecamp3'
📲 Updated app: 'cal-ai'
📲 Updated app: 'caldav-calendar'
📲 Updated app: 'campfire'
📲 Updated app: 'closecom'
📲 Updated app: 'cron'
📲 Updated app: 'daily-video'
📲 Updated app: 'discord'
📲 Updated app: 'eightxeight'
📲 Updated app: 'element-call'
📲 Updated app: 'exchange2013-calendar'
📲 Updated app: 'exchange2016-calendar'
📲 Updated app: 'exchange'
📲 Updated app: 'facetime'
📲 Updated app: 'fathom'
📲 Updated app: 'ga4'
📲 Updated app: 'giphy'
📲 Updated app: 'google-calendar'
📲 Updated app: 'google-meet'
📲 Updated app: 'gtm'
📲 Updated app: 'hubspot'
📲 Updated app: 'huddle01'
📲 Updated app: 'jitsi'
📲 Updated app: 'lark-calendar'
📲 Updated app: 'make'
📲 Updated app: 'metapixel'
📲 Updated app: 'mirotalk'
📲 Updated app: 'n8n'
📲 Updated app: 'office365-calendar'
📲 Updated app: 'msteams'
📲 Updated app: 'paypal'
📲 Updated app: 'ping'
📲 Updated app: 'pipedream'
📲 Updated app: 'plausible'
📲 Updated app: 'qr_code'
📲 Updated app: 'raycast'
📲 Updated app: 'riverside'
📲 Updated app: 'routing-forms'
📲 Updated app: 'salesforce'
📲 Updated app: 'sendgrid'
📲 Updated app: 'signal'
📲 Updated app: 'sirius_video'
📲 Updated app: 'skiff'
📲 Updated app: 'stripe'
📲 Updated app: 'sylapsvideo'
📲 Updated app: 'tandem'
📲 Updated app: 'telegram'
📲 Updated app: 'typeform'
📲 Updated app: 'vimcal'
📲 Updated app: 'vital-automation'
📲 Updated app: 'weather_in_your_calendar'
📲 Updated app: 'webex'
📲 Updated app: 'whatsapp'
📲 Updated app: 'whereby'
Updated app: 'wipe-my-cal'
📲 Updated app: 'wordpress'
📲 Updated app: 'zapier'
📲 Updated app: 'zoho-bigin'
📲 Updated app: 'zohocrm'
📲 Updated app: 'zoom'
Skipping Routing Form - Seeding - Pro User not found
+ yarn start
Internal Error: @calcom/make@workspace:packages/app-store/make: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at P0.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:435:5145)
    at yf.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:391:1264)
    at /calcom/.yarn/releases/yarn-3.4.1.cjs:439:7693
    at of (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:11070)
    at ge (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:7673)
    at async Promise.allSettled (index 31)
    at async $s (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:10398)
    at async /calcom/.yarn/releases/yarn-3.4.1.cjs:439:8205
    at async ti.startProgressPromise (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:47579)
    at async je.resolveEverything (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:6233)
```

### Expected Results
We expected the calcom application to start without any errors.

### Technical details
- Docker Image: Official Docker Hub image
- Node.js version: [Please specify the Node.js version used in your Docker environment.]

### Docker Compose Configuration
Here's the Docker Compose configuration used:

```yml
services:
  calcom:
    container_name: calcom
    image: calcom/cal.com
    environment:
      DATABASE_URL: 'postgresql://calcom_user:strong_password@postgres-calcom:5432/calcom_db'
      NEXTAUTH_SECRET: 'secdrftgyhujikl637GHZJEDK28ret'
      CALENDSO_ENCRYPTION_KEY: 'rtfyguhijoklrdytftygufguhijip'
      NEXT_PUBLIC_WEBAPP_URL: 'https://{{ calcom_domain }}'
    networks:
      - traefik-backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-backend"
      - "traefik.http.routers.calcom.entrypoints=websecure"
      - "traefik.http.routers.calcom.rule=Host(`{{ calcom_domain }}`) || Host(`www.{{ calcom_domain }}`)"
      - "traefik.http.routers.calcom.tls=true"
      - "traefik.http.routers.calcom.tls.certresolver=myresolver"
      - "traefik.http.services.calcom.loadbalancer.server.port=3000"
    volumes:
      - calcom_data:/calcom/data

  postgres-calcom:
    container_name: postgres-calcom
    image: postgres:latest
    environment:
      POSTGRES_USER: calcom_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: calcom_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik-backend

volumes:
  calcom_data:
  postgres_data:

networks:
  traefik-backend:
    external: true
```

❓❓❓

Internal Error: @calcom/make@workspace:packages/app-store/make: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile

**Comment by Maximilian-Pichler** [comment]
same issue with same error message here.
Tested it with the docker-compose.yml file from @kevingrondin and the one below

```
version: '3.8'

services:
  calcom_db:
    container_name: calcom_db
    image: postgres
    restart: always
    volumes:
      - ./data/calcom/db:/var/lib/postgresql/data/
    env_file: ./data/calcom/.env
    networks:
      vlan:
        ipv4_address: xxx.xxx.xxx.xxx
    ports:
      - 5432:5432

  calcom:
    container_name: calcom
    image: calcom.docker.scarf.sh/calcom/cal.com
    #image: calendso/calendso:latest
    build:
      context: ./data/calcom/docker/
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL: ${NEXT_PUBLIC_WEBAPP_URL}
        NEXT_PUBLIC_LICENSE_CONSENT: ${NEXT_PUBLIC_LICENSE_CONSENT}
        CALCOM_TELEMETRY_DISABLED: ${CALCOM_TELEMETRY_DISABLED}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
        DATABASE_URL: ${DATABASE_URL}
    restart: always
    networks:
      vlan:
        ipv4_address: xxx.xxx.xxx.xxx
    ports:
      - 3000:3000
    env_file: ./data/calcom/.env
    depends_on:
      - calcom_db
 ```
