### ISSUE TITLE
Running 3.2.8 with docker fails with error "This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile"

### ISSUE THREAD

**Issue by kolaente** [calcom/cal.com#11297]
### Issue Summary

Updating to 3.2.8 fails with the error mentioned below.

I tried upgrading to 3.2.9, but the docker image is not available.

### Steps to Reproduce

1. Run the image, see below for a docker-compose file

### Actual Results

Container crashes with this error message:

```
calcom_1    | + yarn start
calcom_1    | Internal Error: @calcom/make@workspace:packages/app-store/make: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
calcom_1    |     at P0.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:435:5145)
calcom_1    |     at yf.getCandidates (/calcom/.yarn/releases/yarn-3.4.1.cjs:391:1264)
calcom_1    |     at /calcom/.yarn/releases/yarn-3.4.1.cjs:439:7693
calcom_1    |     at of (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:11070)
calcom_1    |     at ge (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:7673)
calcom_1    |     at async Promise.allSettled (index 31)
calcom_1    |     at async $s (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:10398)
calcom_1    |     at async /calcom/.yarn/releases/yarn-3.4.1.cjs:439:8205
calcom_1    |     at async ti.startProgressPromise (/calcom/.yarn/releases/yarn-3.4.1.cjs:390:47579)
calcom_1    |     at async je.resolveEverything (/calcom/.yarn/releases/yarn-3.4.1.cjs:439:6233)
calcom_calcom_1 exited with code 1
```

### Expected Results

not crashing

### Technical details

Docker compose file used:

```yaml
version: '3.8'

networks:
  stack:
    name: stack
    external: false
  web:
    external: true

services:
  database:
    container_name: database
    image: postgres:14
    restart: always
    volumes:
      - /var/apps/calcom/db:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - stack

  calcom:
    image: calcom/cal.com:v3.2.8
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database
    networks:
      - stack
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.calcom.rule=Host(`cal.example.com`)"
      - "traefik.http.routers.calcom.entrypoints=https"
      - "traefik.http.routers.calcom.tls.certResolver=basic"
      - "traefik.http.services.calcom.loadbalancer.server.port=3000"
```

**Comment by PeerRich** [comment]
lemme look into this. typically the docker image should be created everytime we make a new tagged release

**Comment by kolaente** [comment]
> typically the docker image should be created everytime we make a new tagged release

It's been better since a while now but a while ago (I think before the 3.0 release) docker releases have been lagging behind by days or weeks. See https://github.com/calcom/docker/issues/224 as well.

**Comment by krumware** [comment]
@PeerRich @emrysal this does look like it needs to be fixed in the upstream project here

**Comment by krumware** [comment]
Perhaps not? local build doesn't experience the same error but it's still possible. I'm experiencing this on remote deployments as well. Investigating.

**Comment by krumware** [comment]
@kolaente can you please try calcom/docker:main and see if it resolves this issue for you?

**Comment by kolaente** [comment]
@krumware Tried 3.2.10 (because you've just released it, might as well) and that seems to work.

**Comment by notflip** [comment]
@kolaente Can you please share your working docker-compose file? I can't seem to get it to work using the official one

**Comment by kolaente** [comment]
@notflip sure here you go:

```
# Use postgres/example user/password credentials
version: '3.8'

networks:
  stack:
    name: stack
    external: false
  web:
    external: true

services:
  database:
    container_name: database
    image: postgres:14
    restart: always
    volumes:
      - /var/apps/calcom/db:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - stack

  calcom:
    image: calcom/cal.com:v3.3.6
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
    depends_on:
      - database
    networks:
      - stack
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.calcom.rule=Host(`cal.example.com`)"
      - "traefik.http.routers.calcom.entrypoints=https"
      - "traefik.http.routers.calcom.tls.certResolver=basic"
      - "traefik.http.services.calcom.loadbalancer.server.port=3000"
```

It's based on the official one though

**Comment by notflip** [comment]
@kolaente Thanks, strangely enough I keep getting the errors I got with the default setup as well, did you ever encounter these? https://github.com/calcom/docker/issues/295

**Comment by kolaente** [comment]
@notflip No, didn't have any problems like that.

**Comment by carsonbird** [comment]
I was experiencing the exact same thing in a docker deployment. Turns out I was just using an old container version (v3.2.28, I think). I changed it to "latest" and now it's working.

**Comment by notflip** [comment]
@carsonbird Do you mind sharing your docker-compose file of the working version? Would be of great help, thanks!

**Comment by carsonbird** [comment]
@notflip and anyone else who's suffering. Instructions and files:

# Installation

Here's a quick, from-memory set of instructions. It's mostly based on the [advanced instructions in the Cal.com Docker README](https://github.com/calcom/docker?tab=readme-ov-file#advanced-users-build-and-run-calcom).

1. Fork the cal.com **_Docker_** repository
2. Clone it down: `git clone --recurse-submodules <url>`.
3. Run `git submodule update --remote --init` in the repo folder to get the latest submodule cloned down as well.
4. Use the `.env.example` file to create a `.env` file for your setup.
5. Run `docker compose pull` to get the docker image.
6. Spin up the database so Cal.com can configure it during the build process, or something: `docker compose up -d db`. You might want to omit the `-d` the first time so you can watch the database setup process in `stdout`, then shut it down and restart it with `-d`. You can also use `docker logs -f <servicename>` to watch the logs.
7. Navigate into the `./calcom/` folder of the repo (the actual Cal.com source code), and run `yarn install`, for some reason. I might be remembering this wrong, and maybe you do this after the next step.
8. Build Cal.com: `DOCKER_BUILDKIT=0 docker compose build server` from your repo's root dir.
9. In case I was wrong above, run `yarn install` again, though I don't know why that would affect anything at this point (the application should be built and tucked away in its own docker image without any external dependencies or file access).
10. Spin up the container with `docker compose up -d`. Omit the `-d` if you want to watch the setup process in your terminal.
11. You should be good to go after that. My setup is using this config for Cal.com; routing, certs, load balancing, etc with Traefik in another container.

_I've spent a while developing this setup (for Cal.com and lots of other services), but I'm by no means an expert, so if you see glaring issues or opportunities for optimization, please let me know!_

# Files

## docker-compose.yaml

```yaml
# ────────────────────────────────────────────────────────────────────────────╮
# ┌─┐┬─┐┌─┐┌┬┐┬ ┬┌─┐┌┬┐┬┌─┐┌┐┌  ┌┬┐┌─┐┌─┐┬  ┌─┐┬ ┬┌┬┐┌─┐┌┐┌┌┬┐
# ├─┘├┬┘│ │ │││ ││   │ ││ ││││   ││├┤ ├─┘│  │ │└┬┘│││├┤ │││ │
# ┴  ┴└─└─┘─┴┘└─┘└─┘ ┴ ┴└─┘┘└┘  ─┴┘└─┘┴  ┴─┘└─┘ ┴ ┴ ┴└─┘┘└┘ ┴
#
# This file is for deploying the project in a production environment.
#
# You can spin up a production-ready application stack with the following:
# ```bash
# docker compose up -d
# ```
# ────────────────────────────────────────────────────────────────────────────╯
version: "3.8"

# ███╗   ██╗███████╗████████╗██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗███████╗
# ████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝██╔════╝
# ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║██║   ██║██████╔╝█████╔╝ ███████╗
# ██║╚██╗██║██╔══╝     ██║   ██║███╗██║██║   ██║██╔══██╗██╔═██╗ ╚════██║
# ██║ ╚████║███████╗   ██║   ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗███████║
# ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝

networks:
  private:
    name: ${COMPOSE_PROJECT_NAME}_private
  public:
    name: ${COMPOSE_PROJECT_NAME}_public

# ███████╗███████╗██████╗ ██╗   ██╗██╗ ██████╗███████╗███████╗
# ██╔════╝██╔════╝██╔══██╗██║   ██║██║██╔════╝██╔════╝██╔════╝
# ███████╗█████╗  ██████╔╝██║   ██║██║██║     █████╗  ███████╗
# ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██║██║     ██╔══╝  ╚════██║
# ███████║███████╗██║  ██║ ╚████╔╝ ██║╚██████╗███████╗███████║
# ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚═╝ ╚═════╝╚══════╝╚══════╝

services:
  # ────────────────────────────────────────────────────────────────────────────╮
  # ┌─┐┌─┐┬─┐┬  ┬┌─┐┬─┐
  # └─┐├┤ ├┬┘└┐┌┘├┤ ├┬┘
  # └─┘└─┘┴└─ └┘ └─┘┴└─
  # ────────────────────────────────────────────────────────────────────────────╯
  server:
    container_name: ${COMPOSE_PROJECT_NAME}_${SERVER_CONTAINER_NAME}
    image: calcom.docker.scarf.sh/calcom/cal.com:${SERVER_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL: https://${SERVER_SUBDOMAIN}.${HOSTNAME}
        NEXT_PUBLIC_LICENSE_CONSENT: true
        NEXTAUTH_DOMAIN: ${SERVER_SUBDOMAIN}.${HOSTNAME}
        # NEXTAUTH_URL: https://${SERVER_SUBDOMAIN}.${HOSTNAME}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        CALCOM_TELEMETRY_DISABLED: 1
        CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
        DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_SUBDOMAIN}:5432/${COMPOSE_PROJECT_NAME}
      network: ${COMPOSE_PROJECT_NAME}_private
    restart: unless-stopped
    networks:
      - private
      - public
    expose:
      - ${SERVER_PORT:-3000}
    labels:
      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      # Traefik Config
      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      - traefik.enable=true
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}_public

      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      # Services
      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}_${SERVER_CONTAINER_NAME}.service=${COMPOSE_PROJECT_NAME}_${SERVER_CONTAINER_NAME}
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_${SERVER_CONTAINER_NAME}.loadbalancer.server.port=${SERVER_PORT:-3000}

      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      # Entrypoints
      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}_${SERVER_CONTAINER_NAME}.entrypoints=http,https

      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      # Routers
      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}_${SERVER_CONTAINER_NAME}.rule=Host(`${SERVER_SUBDOMAIN}.${HOSTNAME}`)

      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      # Middleware
      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}_${SERVER_CONTAINER_NAME}.middlewares=redirect->https@file

      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      # TLS
      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}_${SERVER_CONTAINER_NAME}.tls=true
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}_${SERVER_CONTAINER_NAME}.tls.certresolver=letsencrypt
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_SUBDOMAIN}:${DB_PORT:-5432}/${COMPOSE_PROJECT_NAME}
      NEXT_PUBLIC_WEBAPP_URL: https://${SERVER_SUBDOMAIN}.${HOSTNAME}
      NEXT_PUBLIC_LICENSE_CONSENT: true
      NEXTAUTH_DOMAIN: ${SERVER_SUBDOMAIN}.${HOSTNAME}
      # NEXTAUTH_URL: https://${SERVER_SUBDOMAIN}.${HOSTNAME}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
      # GOOGLE_API_CREDENTIALS: ${GOOGLE_API_CREDENTIALS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SERVER_HOST: ${EMAIL_SERVER_HOST}
      EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT}
      EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}
      EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}

  # ────────────────────────────────────────────────────────────────────────────╮
  # ┌┬┐┌─┐┌┬┐┌─┐┌┐ ┌─┐┌─┐┌─┐
  #  ││├─┤ │ ├─┤├┴┐├─┤└─┐├┤
  # ─┴┘┴ ┴ ┴ ┴ ┴└─┘┴ ┴└─┘└─┘
  # ────────────────────────────────────────────────────────────────────────────╯
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_${DB_CONTAINER_NAME}
    image: postgres:${DB_VERSION}
    restart: unless-stopped
    networks:
      - private
    expose:
      - ${DB_PORT:-5432}
    labels:
      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      # Traefik Config
      #
      # The DB isn't accessible from the public network in production, so Traefik
      # is disabled in the production deployment.
      # ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
      - traefik.enable=false
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}

# ██╗   ██╗ ██████╗ ██╗     ██╗   ██╗███╗   ███╗███████╗███████╗
# ██║   ██║██╔═══██╗██║     ██║   ██║████╗ ████║██╔════╝██╔════╝
# ██║   ██║██║   ██║██║     ██║   ██║██╔████╔██║█████╗  ███████╗
# ╚██╗ ██╔╝██║   ██║██║     ██║   ██║██║╚██╔╝██║██╔══╝  ╚════██║
#  ╚████╔╝ ╚██████╔╝███████╗╚██████╔╝██║ ╚═╝ ██║███████╗███████║
#   ╚═══╝   ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝

volumes:
  db:
    name: ${COMPOSE_PROJECT_NAME}_${DB_CONTAINER_NAME}
```

## .env.example

```env
# ────────────────────────────────────────────────────────────────────────────╮
# ┌─┐┬─┐┌─┐ ┬┌─┐┌─┐┌┬┐  ┬  ┬┌─┐┬─┐┬┌─┐┌┐ ┬  ┌─┐┌─┐
# ├─┘├┬┘│ │ │├┤ │   │   └┐┌┘├─┤├┬┘│├─┤├┴┐│  ├┤ └─┐
# ┴  ┴└─└─┘└┘└─┘└─┘ ┴    └┘ ┴ ┴┴└─┴┴ ┴└─┘┴─┘└─┘└─┘
#
# - `COMPOSE_PROJECT_NAME` is used to prefix containers, networks, and 
#   proxying. It is also used to generate the default database name and user.
# - `HOSTNAME` is the base domain name used for proxying the publicly facing 
#   containers, along with their subdomains.
# ────────────────────────────────────────────────────────────────────────────╯

COMPOSE_PROJECT_NAME=calcom
HOSTNAME=your.parent.hostname.com

# ────────────────────────────────────────────────────────────────────────────╮
# ┌┬┐┌─┐┌┬┐┌─┐┌┐ ┌─┐┌─┐┌─┐
#  ││├─┤ │ ├─┤├┴┐├─┤└─┐├┤
# ─┴┘┴ ┴ ┴ ┴ ┴└─┘┴ ┴└─┘└─┘
# ────────────────────────────────────────────────────────────────────────────╯

DB_CONTAINER_NAME=database
DB_SUBDOMAIN=db
DB_VERSION=15.4-alpine3.18
DB_USER=
DB_PASS=

# ────────────────────────────────────────────────────────────────────────────╮
# ┌─┐┌─┐┬─┐┬  ┬┌─┐┬─┐
# └─┐├┤ ├┬┘└┐┌┘├┤ ├┬┘
# └─┘└─┘┴└─ └┘ └─┘┴└─
# ────────────────────────────────────────────────────────────────────────────╯

SERVER_CONTAINER_NAME=server
SERVER_SUBDOMAIN=cal # Using Traefik configuration, the server will be accessible at cal.your.parent.hostname.com
SERVER_VERSION=latest

# Generate with `openssl rand -base64 32` per https://next-auth.js.org/configuration/options#secret
NEXTAUTH_SECRET=

# Encryption key that will be used to encrypt CalDAV credentials, choose a random string.
# For example, generate with `dd if=/dev/urandom bs=1K count=1 | md5sum`
CALENDSO_ENCRYPTION_KEY=

GOOGLE_API_CREDENTIALS={} # Raw JSON string of Google API credentials

# Used for the Zoom integration
# ZOOM_CLIENT_ID=
# ZOOM_CLIENT_SECRET=

# E-mail settings
# Configures the global From: header whilst sending emails.
EMAIL_FROM=

# Configure SMTP settings (@see https://nodemailer.com/smtp/).
EMAIL_SERVER_HOST=smtp.example.com
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER=email_user
EMAIL_SERVER_PASSWORD=email_password

NODE_ENV=production
```
