### ISSUE TITLE
Two hours less time difference in Nextcloud Web 

### ISSUE THREAD

**Issue by aukfood** [calcom/cal.com#15368]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When we create an event with cal.com integrated with Nextcloud agenda, we have two hours less time difference.

### Steps to Reproduce

1. create an event with cal.com installed in docker environment.
2. see informations in Thunderbird ok
3. see informations in Nextcloud Agenda not ok

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

![nextcloud-agenda](https://github.com/calcom/cal.com/assets/67263702/5b8fbe0c-1702-45ff-b2cf-25370eba9427)

![thunderbird-agenda](https://github.com/calcom/cal.com/assets/67263702/61228e8a-45f0-432d-b62c-de8d99ec1af2)

### Technical details

- debian 12
- docker latest version
- nextcloud 27 and 29
- nextcloud in french language

Thanks

**Comment by aukfood** [comment]
What I see is that information in Nextcloud database is not registred with the good hour. For example I create an event for 20240614 at 10h30 am and in Nextcloud database is registred at **DTSTART:20240614T083000Z**

So if I create an event in Netcloud at 20240613 at 13h30 event is like that in database : **DTSTART;TZID=Europe/Paris:20240613T133000**

So I think that cal.com is not registred correctly time in nextcloud database. How to see timezone in cal.com container ?

Regards

**Comment by aukfood** [comment]
Date in container is not good 
```
b71d7c2b9a7f:/calcom# date
Wed Jun 12 16:27:48  2024
```

I try to add this in docker-compose 
```
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
      - TZ="Europe/Paris"
    depends_on:
      - database
    volumes:
      - "/etc/timezone:/etc/timezone:ro" 
 ```
