### ISSUE TITLE
Slack app, how to share event type with users 

### ISSUE THREAD

**Issue by starpunjabi** [calcom/cal.com#2469]
/craete-event is working but /links is not working
How can we share event types with slack users from slack app?

I can't find any documentation as well for this.

**Comment by milospuac** [comment]
Hi there. We are currently doing some work on /links command. Once it's done our documentation will be updated as well

Thank you for your patience.

**Comment by sean-brydon** [comment]
For the /links command the Cal.com Bot has to have access to the workspace/channel you are talking in. 

We are currently looking to make this more obvious/easy for the user when it comes to adding the bot to channels.

**Comment by starpunjabi** [comment]
In cal.com application, we are creating event types and sharing url with our friends so they can get privilege to choose their date and time for meeting. But when using in slack, How to share event type with slack users, so they can choose their day and time stam, like how we are sharing in cal.com application.
I tested it for calendly and calendly has a command to share event type with slack users, but this functionality is not available in cal.com. IN cal.com /create-event command is used to share event type but user had to select booking date, and users as well. So there is no way current to share only event type. Please implement that as well similar to calendly. Thanks

**Comment by sean-brydon** [comment]
So from what I’ve gathered - you have already created the booking and would like to share that with members of slack?

**Comment by starpunjabi** [comment]
![image](https://user-images.githubusercontent.com/20169304/163824554-585f793c-3a5e-4176-ba29-99e9cff4d0b5.png)

**Comment by starpunjabi** [comment]
![image](https://user-images.githubusercontent.com/20169304/163825514-f500e474-0a82-4a27-bb1b-c2e9481e330e.png)

**Comment by sean-brydon** [comment]
This feature is implemented within the /links command. Note: The Cal.com Bot needs to be added to the workspace and have permission to talk in the channel. If you are self hosting you can add "chat:write.public" to the bot permissions to allow it to talk in any channel within the workspace.

**Comment by starpunjabi** [comment]
I am not getting how to add permission to talk in the channel or how to enable /links, and /links for me is not working. I am able to use /create-events properly, and even it is showing all event-types too. but /links is not working at all. 

![image](https://user-images.githubusercontent.com/20169304/163859177-fe90ab42-1127-44ca-ae58-9e15db622ad0.png)

![image](https://user-images.githubusercontent.com/20169304/163859813-9405a436-5779-4e08-933b-fa92d35e0a58.png)

**Comment by sean-brydon** [comment]
Please can you try adding the bot to the channel you are talking in - or since you are self hosted can you try going into the slack bot settings and adding the chat:write.public scope to the bot and the reconnecting the bot to your workspace.

**Comment by starpunjabi** [comment]
![image](https://user-images.githubusercontent.com/20169304/163984651-91706063-db01-45a3-a7b1-a39b4586d10a.png)

I am not getting how to add in slack setting permission like chat:write.public scope, can you help me or share any resource link or stackoverflow message.

**Comment by starpunjabi** [comment]
![image](https://user-images.githubusercontent.com/20169304/163984651-91706063-db01-45a3-a7b1-a39b4586d10a.png)

I am not getting how to add in slack setting permission like chat:write.public scope, can you help me or share any resource link or stackoverflow message.

**Comment by sean-brydon** [comment]
@starpunjabi  Course Sorry! If you goto the slack app (https://api.slack.com/apps) and click on your bot. Goto app-manifest and you should see a Scopes section within YAML. 

It should look something like this 
```
display_information:
 name: Cal.com Slack
features:
 bot_user:
   display_name: Cal.com Slack
   always_online: false
 slash_commands:
   - command: /create-event
     url: https://YOUR_DOMAIN/api/integrations/slackmessaging/commandHandler
     description: Create an event within Cal!
     should_escape: false
   - command: /today
     url: https://YOUR_DOMAIN/api/integrations/slackmessaging/commandHandler
     description: View all your bookings for today
     should_escape: false
oauth_config:
 redirect_urls:
   - https://YOUR_DOMAIN/api/integrations/slackmessaging/callback
 scopes:
   bot:
     - chat:write
     - commands
     - chat:write.public 
settings:
 interactivity:
   is_enabled: true
   request_url: https://YOUR_DOMAIN/api/integrations/slackmessaging/interactiveHandler
   message_menu_options_url: https://YOUR_DOMAIN/api/integrations/slackmessaging/interactiveHandler
 org_deploy_enabled: false
 socket_mode_enabled: false
 token_rotation_enabled: false
```
