### ISSUE TITLE
Selfhosted calcom docker is not changing base or webapp URL - Only localhost  | Environment variables issues

### ISSUE THREAD

**Issue by pbdco** [calcom/cal.com#3672]
I am running calendso in production, using docker. After I start the containers, I access to my CAL website (example: "cal.mydomain.com"), but I notice that **the base URL is still http://localhost:3000, even if the .env and docker-compose is set correctly.**

Example:

- At site admin, I see the base URL is still localhost:
![image](https://user-images.githubusercontent.com/64397076/182633577-f46507b8-5dc1-4729-8c7f-18b82e7fe3a2.png)

- At /event-types, when I copy one of my event links, the link is copied with http://localhost:3000/user/etc....

- I notice there is some kind of issue with env variables, because I still see the license agreement bar event if I have set NEXT_PUBLIC_LICENSE_CONSENT=agree in my .env file.

![image](https://user-images.githubusercontent.com/64397076/182634351-b932fddf-ae1d-48e7-8d39-1a3270cbcada.png)

---------------

My .env file:

```
NEXT_PUBLIC_LICENSE_CONSENT=agree
LICENSE=

BASE_URL=https://cal.mydomain.com
NEXT_PUBLIC_WEBAPP_URL=https://cal.mydomain.com
NEXT_PUBLIC_APP_URL=https://cal.mydomain.com

POSTGRES_USER=postgres
POSTGRES_PASSWORD=example
POSTGRES_DB=calendso
DATABASE_HOST=database:5432
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
GOOGLE_API_CREDENTIALS={}

# Remove this var if you don't want Calendso to collect anonymous usage
#NEXT_PUBLIC_TELEMETRY_KEY=123321123

CALCOM_TELEMETRY_DISABLED=true
NEXTAUTH_SECRET=123321123
NEXTAUTH_URL=https://cal.mydomain.com

# Used for the Office 365 / Outlook.com Calendar integration
MS_GRAPH_CLIENT_ID=
MS_GRAPH_CLIENT_SECRET=

# Used for the Zoom integration
ZOOM_CLIENT_ID=
ZOOM_CLIENT_SECRET=

# E-mail settings
# Configures the global From: header whilst sending emails.
EMAIL_FROM=cal@mydomain.com

# Configure SMTP settings (@see https://nodemailer.com/smtp/).
EMAIL_SERVER_HOST=mail.mydomain.com
EMAIL_SERVER_PORT=587
EMAIL_SERVER_USER=cal@mydomain.com
EMAIL_SERVER_PASSWORD=example

# Encryption key that will be used to encrypt CalDAV credentials, choose a random string, for example with `dd if=/dev/urandom bs=1K count=1 | md5sum`
CALENDSO_ENCRYPTION_KEY=123321123

# It is highly recommended that the JWT secret must be overridden and very unique
JWT_SECRET=secret

NODE_ENV=production
```

My docker-compose.yaml:

```
version: '3.1'

services:
  database:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    env_file: .env
    expose:
      - 5432
    networks:
      - calendso

  calendso:
    image: calendso/calendso:latest
    restart: unless-stopped
    expose:
      - 3000
    env_file: .env
    environment:
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_LICENSE_CONSENT=${NEXT_PUBLIC_LICENSE_CONSENT}
      - CALCOM_TELEMETRY_DISABLED=${CALCOM_TELEMETRY_DISABLED}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
      - NODE_ENV={$NODE_ENV}
      - VIRTUAL_HOST=cal.mydomain.com
      - LETSENCRYPT_HOST=cal.mydomain.com
      - VIRTUAL_PORT=3000
    depends_on:
      - database
    networks:
      - nginx-proxy
      - calendso
```

PS: I am running docker behind a reverse proxy using nginx-proxy.
