### ISSUE TITLE
Self hosted url stuck at localhost:3000

### ISSUE THREAD

**Issue by gone** [calcom/cal.com#8501]
### Issue Summary

When self hosting the url is stuck at localhost:3000

### Steps to Reproduce

1. use "install to render" button
2. Set any/all of the  nextauth_url, NEXT_PUBLIC_* envrionment values to the correct host
3. Host is still on localhost:3000

**Comment by marcoantonio123456** [comment]
same here

**Comment by pranjalg13** [comment]
@gone have you tried changing it to 127.0.0.1:3000 IP instead of localhost

**Comment by Draidel** [comment]
I believe it is related to the .yaml that docker uses.
 I forked https://github.com/calcom/docker, adjusted the .yaml file and pushed to the server again. It fixed SOME occurrences, but I there are still some issues

**Comment by vsviridov** [comment]
Installed locally, modified the `.env` file with the full `https://` url for `NEXT_PUBLIC_WEBAPP_URL` etc, and after login I still get bounced back to `http://localhost:3000`.

**Comment by oksdav** [comment]
I believe it's because Next.js uses port 3000 by default.
Try one of these, in addition to changing the NEXT_PUBLIC_* environment variables:
- Adding `-p <PORT_NUMBER>` after `next dev`/`next start` in apps/web/package.json
- Running `yarn dev -- -p <PORT_NUMBER>`/`yarn start -- -p <PORT_NUMBER>`

**Comment by ur3an0** [comment]
same problem here
![image](https://github.com/calcom/cal.com/assets/1440851/29ab9ec9-9e36-4b03-a3bd-ff8ca87681bc)

**Comment by Sharma-Rajat** [comment]
same issue here

**Comment by webenggeo** [comment]
Has anyone solved this?

**Comment by sudo-eugene** [comment]
+1
<img width="508" alt="Screenshot 2023-10-10 at 07 47 48" src="https://github.com/calcom/cal.com/assets/145440622/7d856fd9-a4c8-4c2c-b3a2-b10a218a0560">

**Comment by ddilushan** [comment]
same issue here

**Comment by Fritofour** [comment]
Same problem. Can anynone look into it? :'(

**Comment by Fritofour** [comment]
Looks like I found my problem. Just added the .env in the turbo.env.

`"$schema": "https://turborepo.org/schema.json",
  "globalDotEnv": [".env"],
  "pipeline": {
`

**Comment by lperrious** [comment]
After updating the .env file, refreshing the cache worked for me.

**Comment by gutocarvalho** [comment]
Same here, in some links it's still point to localhost:3000

**Comment by persuasive0pest** [comment]
It's been a year, I guess this won't be fixed anymore, maybe consider fork and fix on our own.

**Comment by persuasive0pest** [comment]
It turns out calcom is using next.js 13 and still using pages router, [a quick search revealed how these environment variable is used.](https://github.com/search?q=repo%3Acalcom%2Fcal.com+process.env.NEXT_PUBLIC_&type=code)
[The next.js doc suggest](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables) one should try to use `getServerSideProps` so environment variables can be read at runtime dynamically, I'll do a proof of concept shortly.

**Comment by persuasive0pest** [comment]
I'm gradually fixing this by replacing most client side environment variables to incorporate `getServerSideProps` instead so they will be rendered at request time.
I was a able to get it working in 2 places as of today.
https://github.com/calcom/cal.com/compare/main...persuasive0pest:cal.com:main

**Comment by opiredev** [comment]
@nabby27 created a $30.00 reward using [Opire](https://opire.dev) 
 <details><summary>How to earn this reward?</summary>

Since this project does not have Opire bot installed yet 😞 you need to go to [Opire](https://app.opire.dev) and claim the rewards through your programmer's dashboard once you have your PR ready 💪</details>

**Comment by nabby27** [comment]
Hi 👋🏼 I created this reward because I would like to see this issue solved, maybe it's not enough but it's what I can offer if others put in their bit we can incentive some devs to solve this

**Comment by persuasive0pest** [comment]
According to a quick search it seems there are other instances of `NEXT_PUBLIC_WEBAPP_URL` being used elsewhere:
https://github.com/search?q=repo%3Acalcom%2Fcal.com%20NEXT_PUBLIC_WEBAPP_URL&type=code
I'm not immediately able to identify if they are being imported into frontend via transitive dependency, I'll try to find a tool to assist with the investigation.

There is one outstanding variable `WEBAPP_URL` located in:
https://github.com/calcom/cal.com/blob/26bd02bd9409123f50f3501471738da66554f558/packages/lib/constants.ts#L11

That is imported into frontend but it's not in `app` folder.
To properly handle it I'll create a context provider and feed all such variables from there, until all of them are taken care of.
The context provider itself will be loading the values from `getServerSideProps` dynamically at runtime to ensure they reflect the desired value as expected.

**Comment by fehzl** [comment]
To resolve this issue for the Docker build, follow these steps:

1. Remove the `BUILT_NEXT_PUBLIC_WEBAPP_URL` environment variable or set its value to `http://localhost:3000`.
2. Set the `NEXT_PUBLIC_WEBAPP_URL` environment variable to your desired URL.

Refer to the following note from the solution reference:

```
# Replace the statically built BUILT_NEXT_PUBLIC_WEBAPP_URL with run-time NEXT_PUBLIC_WEBAPP_URL
# NOTE: if these values are the same, this will be skipped.
```

You can check the reference here: [GitHub Reference](https://github.com/calcom/docker/blob/main/scripts/start.sh).

**Comment by netzpixel** [comment]
still no solution to this?...

**Comment by JuanxCursed** [comment]
Any updates? Same issue here

**Comment by JackPala** [comment]
Same issue here.

**Comment by JuanxCursed** [comment]
I managed to make work using Coolify setup WITHOUT setting up SMTP, It will broke completely

**Comment by teamgroove** [comment]
I lost hours to this alone and finally gave up. 
Do you know how many human hours got wasted by this collectively?

**Comment by JackPala** [comment]
> I lost hours to this alone and finally gave up. Do you know how many human hours got wasted by this collectively?

Quite a few. Make sure if you are self hosting docker to use 4.5.1 because all versions after that are broken for almost everybody.

Once you get it to work it's a very good tool, but the next.js route wrestling makes it finnicky. 

Try deleting the volume every time you rebuild the docker container if using docker. And for sure use docker if self hosting, the docker compose makes it so you can purge the install as many times as needed. 

What fixed it for me was a full purge of the docker volume, a rebuild using only the ENV as the source, and then connecting to it via my reverse proxy.

**Comment by satoshinotdead** [comment]
@JackPala so are you using localhost? Please, can you share your Nginx template?

**Comment by JackPala** [comment]
> @JackPala so are you using localhost? Please, can you share your Nginx template?

I am using a Caddy Reverse Proxy, and my main install is running as a docker compose, here is my docker compose 

```
# Use postgres/example user/password credentials
version: '3.8'

volumes:
  database-data:

networks:
  stack:
    name: stack
    external: false

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - stack

  calcom:
    image: calcom/cal.com:v4.5.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL: ${NEXT_PUBLIC_WEBAPP_URL}
        NEXT_PUBLIC_API_V2_URL: ${NEXT_PUBLIC_API_V2_URL}
        NEXT_PUBLIC_LICENSE_CONSENT: ${NEXT_PUBLIC_LICENSE_CONSENT}
        CALCOM_TELEMETRY_DISABLED: ${CALCOM_TELEMETRY_DISABLED}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
        DATABASE_URL: ${DATABASE_URL}
        DATABASE_DIRECT_URL: ${DATABASE_URL}
      network: stack
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
      - DATABASE_DIRECT_URL=${DATABASE_URL}
    depends_on:
      - database

# Optional use of Prisma Studio. In production, comment out or remove the section below to prevent unwanted access to your database.
  studio:
    image: calcom/cal.com:v4.5.1
    restart: always
    networks:
      - stack
    ports:
      - 5555:5555
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
      - DATABASE_DIRECT_URL=${DATABASE_URL}
    depends_on:
      - database
    command:
      - npx
      - prisma
      - studio
# END SECTION: Optional use of Prisma Studio.
```
