### ISSUE TITLE
/ Redirect doesnt appear to be working on self hosting

### ISSUE THREAD

**Issue by mrkirchner** [calcom/cal.com#9768]
### Issue Summary

When login or just hitting root domain, i see the following screenshot.  This happens on a deploy of a self hosted instance and does not appear if i run the code locally.  

<img width="862" alt="Screenshot 2023-06-23 at 1 20 35 PM" src="https://github.com/calcom/cal.com/assets/13805753/f9d74398-9737-4130-abeb-170962685796">

### Steps to Reproduce

1. Deploy a self hosted instance and login
2. Observe 404 page (username / is still available)

### Technical details

- Deployed this both on vercel and Digital ocean.

**Comment by shammirbaig** [comment]
Happened with me too

**Comment by cpunnelliehealth** [comment]
Happened to me too, fine with 2.9.8 but started seeing this in 3.0.5+

Checked .env file, everything is in order and works locally yarn dev, but getting this error when deployed self hosted.

**Comment by mariushosting** [comment]
Bug confirmed on selfhosted since 2 weeks.

**Comment by PeerRich** [comment]
we are investigating this immediately! my apologies

**Comment by hariombalhara** [comment]
Can someone confirm if it happens on v3.0.6 as well? Debugging in the meantime.

**Comment by mariushosting** [comment]
> Can someone confirm if it happens on v3.0.6 as well? Debugging in the meantime.

Yes happen in 3.0.6 as well. Latest 3.0.6 here: https://calcom.mariushosting.synology.me/

**Comment by hariombalhara** [comment]
Thanks for the confirmation. It helped narrowing down the bug. If it's quick for you, can you try reducing the host to something like calcom.synology.me i.e. with 2 dots and see if it works.

**Comment by mariushosting** [comment]
> Thanks for the confirmation. It helped narrowing down the bug. If it's quick for you, can you try reducing the host to something like calcom.synology.me i.e. with 2 dots and see if it works.

I can't test this since I can add only subdomain. Has worked perfectly and works perfectly with version 2.9.8 and earlier versions

**Comment by hariombalhara** [comment]
No worries. Can you also help me with your NEXT_PUBLIC_WEBAPP_URL env variable value.

**Comment by mariushosting** [comment]
> No worries. Can you also help me with your NEXT_PUBLIC_WEBAPP_URL env variable value.

![value](https://github.com/calcom/cal.com/assets/37554361/fedc0734-30e8-4af9-a3ca-3591e84a1ce1)

**Comment by cpunnelliehealth** [comment]
If it helps, I see an error message I see on the server side that throws type error Invalid URL, and the URL it references is formatted like: "http,https://mycalserverurl.com"

I'm not sure it's supposed to be adding the http, at the beginning and my .env APP_URL is set using the full https://mycalserverurl.com address (without the http at the beginning)

**Comment by hariombalhara** [comment]
@cpunnelliehealth Can you confirm the NEXT_PUBLICK_WEBAPP_URL env variable.

**Comment by cpunnelliehealth** [comment]
I realize I didn't put the actual host URL, since it's a private development server but it does contain 3 dots in the URL eg., cal.dev.privatedomain.com

**Comment by carsonbird** [comment]
I'm also seeing this issue. My domain is `https://meet.*********.us`, and it's behind a reverse proxy. Not sure what the issue is...

**Comment by hariombalhara** [comment]
Yes, it's in main. I specifically tested with your domain locally. So that's weird. 
Do you have the deployment somewhere?

**Comment by mariushosting** [comment]
> Yes, it's in main. I specifically tested with your domain locally. So that's weird. Do you have the deployment somewhere?

https://cal.mariushosting.synology.me/

Fresh installation same issue new server.

**Comment by mariushosting** [comment]
The issue is still not fixed for selfhosted. Only with version v2.9.8 work

**Comment by mariushosting** [comment]
![cal](https://github.com/calcom/cal.com/assets/37554361/2b0e8ffd-b59c-4a8d-b4cc-b07979329b80)

**Comment by hariombalhara** [comment]
@mariushosting Possible to get on a call to quickly solve this ?

**Comment by mariushosting** [comment]
Yes please use the WhatsApp button at the bottom of my page. https://mariushosting.com/

**Comment by hariombalhara** [comment]
Had a call with @mariushosting. Thanks @mariushosting 🙏
The issue is that the docker image with the fix hasn't been released yet. It would be fixed in v3.0.9 after the docker image has been tagged.

So, for people who aren't using docker and using latest main, the issue should be fixed
For people using docker, please wait for new image to be there. cc @krumware for the new image.

@keithwillcode @PeerRich I think @krumware will be able to make the new image once it's tagged.

**Comment by krumware** [comment]
Thanks @hariombalhara I'll be on the lookout

**Comment by keithwillcode** [comment]
https://github.com/calcom/cal.com/releases/tag/v3.0.9 Tagged!

**Comment by mariushosting** [comment]
@hariombalhara @krumware @keithwillcode Everything works like a charm now! Just tested it! Thanks for the update!

**Comment by krumware** [comment]
Glad it's working! New image will be pushed in a few minutes. There is a nightly build available but 'latest' reflects the most recent release. Maybe the fix was actually available in yesterday's image but it hadn't been pulled.

**Comment by MarioNoll** [comment]
Just updated to docker image 3.0.9 but still get a 404, let me know if there any info I can share to help.

**Comment by mariushosting** [comment]
> Just updated to docker image 3.0.9 but still get a 404, let me know if there us any info I can share to help.

I can't replicate this issue, maybe you have an older cache of network somewhere else. No issue on my part everything works like a charm.

**Comment by krumware** [comment]
I've seen some wonky behavior on mine as well the past week or so, at least on a fresh installation, but haven't had a chance to go through it with  a comb. I think I've been seeing a mismatch with the redirect versus the app_url, but can't confirm the cause/effect.

**Comment by carsonbird** [comment]
There was a pull request to fix this, but I'm still experiencing the issue on a fresh install. My full domain host only ever had 2 periods.

**Comment by hariombalhara** [comment]
@carsonbird Is it possible for you to deploy the instance somewhere. I can then debug it. 
1.  Are you using docker?
2. Can you confirm the tag you are using?

**Comment by carsonbird** [comment]
@hariombalhara The instance is deployed publicly - I can get you the URL somehow. Any recommendations to conserve privacy?

I am using docker. I'm using the `latest` tag (see below - my `.env` file has `SERVER_VERSION=latest`.

```yaml
version: '3.8'

networks:
  public:
    name: ${COMPOSE_PROJECT_NAME}-public
  private:
    name: ${COMPOSE_PROJECT_NAME}-private
    external: false

services:
  server:
    container_name: ${COMPOSE_PROJECT_NAME}-${SERVER_SUBDOMAIN}
    image: calcom.docker.scarf.sh/calcom/cal.com:${SERVER_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL: https://${SERVER_SUBDOMAIN}.${HOSTNAME}
        NEXT_PUBLIC_LICENSE_CONSENT: true
        NEXTAUTH_DOMAIN: ${SERVER_SUBDOMAIN}.${HOSTNAME}
        # NEXTAUTH_URL: https://${SERVER_SUBDOMAIN}.${HOSTNAME}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        CALCOM_TELEMETRY_DISABLED: 1
        CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
        DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_SUBDOMAIN}:5432/${COMPOSE_PROJECT_NAME}
      network: ${COMPOSE_PROJECT_NAME}-private
    restart: unless-stopped
    networks:
      - private
      - public
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.docker.network=${COMPOSE_PROJECT_NAME}-public
      
      ### Entrypoints ###
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}-${SERVER_SUBDOMAIN}.entrypoints=http,https

      ### Routers ###
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}-${SERVER_SUBDOMAIN}.rule=Host(`${SERVER_SUBDOMAIN}.${HOSTNAME}`)

      ### Middlewares ###
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}-${SERVER_SUBDOMAIN}.middlewares=redirect->https@file

      ### TLS ###
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}-${SERVER_SUBDOMAIN}.tls=true
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}-${SERVER_SUBDOMAIN}.tls.certresolver=letsencrypt

      ### Service ###
      - traefik.http.routers.router->${COMPOSE_PROJECT_NAME}-${SERVER_SUBDOMAIN}.service=${COMPOSE_PROJECT_NAME}-${SERVER_SUBDOMAIN}
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-${SERVER_SUBDOMAIN}.loadbalancer.server.port=3000
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_SUBDOMAIN}:5432/${COMPOSE_PROJECT_NAME}
      NEXT_PUBLIC_WEBAPP_URL: https://${SERVER_SUBDOMAIN}.${HOSTNAME}
      NEXT_PUBLIC_LICENSE_CONSENT: true
      NEXTAUTH_DOMAIN: ${SERVER_SUBDOMAIN}.${HOSTNAME}
      # NEXTAUTH_URL: https://${SERVER_SUBDOMAIN}.${HOSTNAME}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
      GOOGLE_API_CREDENTIALS: ${GOOGLE_API_CREDENTIALS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SERVER_HOST: ${EMAIL_SERVER_HOST}
      EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT}
      EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}
      EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
    depends_on:
      - db
  
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-${DB_SUBDOMAIN}
    image: postgres:${DB_VERSION}
    restart: unless-stopped
    networks:
      - private
    expose:
      - 5432
    labels:
      - traefik.enable=false
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}

volumes:
  db:
    name: ${COMPOSE_PROJECT_NAME}-${DB_SUBDOMAIN}
```
